Fix show title in the push notification
microsoft/appcenter-sdk-android pull request #1493
Opened 2020-12-22 06:30 UTC by AnastasiaKubova

Please have a look at our [guidelines for contributions](https://github.com/microsoft/appcenter-sdk-android/blob/develop/CONTRIBUTING.md) and consider the following before you submit the PR:

* [x] Has `CHANGELOG.md` been updated?
* [x] Are tests passing locally?
* [x] Are the files formatted correctly?
* [x] Did you add unit tests?
* [x] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?
* [x] Did you check UI tests on the sample app? They are not executed on CI.

## Description

The title has not clear information on the push notification during downloading new release.

**Expected behavior**
Title should contains information about downloading release (version and short version)

**Actual behavior**
Title contains `<Untitled>` string instead.

## Related PRs or issues

AB#84082

2020-12-22 07:55 UTC, MatkovIvan requested changes

2020-12-22 07:55 UTC, MatkovIvan commented on sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerRequestTask.java
> +        request.setTitle(String.format("Downloading version %s (%s)", releaseDetails.getShortVersion(), releaseDetails.getVersion()));
This must be localized

2020-12-23 02:46 UTC, guperrot commented on CHANGELOG.md
> +* **[Fix]** Fix show title in the push notification during downloading a new release.
```suggestion
* **[Fix]** Fix showing the title in the push notification while downloading a new release.
```

2020-12-23 09:31 UTC, MatkovIvan requested changes

2020-12-23 09:31 UTC, MatkovIvan commented on sdk/appcenter-distribute/src/main/res/values/appcenter_distribute.xml
>      <!-- TODO: Add translations. -->
@AnastasiaKubova Please add separate task about translations, if it's missing at the moment

2020-12-23 09:31 UTC, MatkovIvan commented on sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerRequestTask.java
> +        request.setTitle(String.format("%s %s (%s)", mTitle, releaseDetails.getShortVersion(), releaseDetails.getVersion()));
You cacn put `%s (%s)` directly to the string (localized). It's required because ordering can be different in some languages

2020-12-23 14:42 UTC, Jamminroot approved these changes

2020-12-23 15:00 UTC, MatkovIvan submitted a review, later dismissed

2020-12-23 15:01 UTC, Jamminroot requested changes
Blocking since I've noticed that CI fails

2020-12-23 15:02 UTC, MatkovIvan reviewed
@AnastasiaKubova please look at CI failure

2020-12-23 20:57 UTC, guperrot commented on sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerRequestTask.java
> +        request.setTitle(String.format("%s %s (%s)", mTitle, releaseDetails.getShortVersion(), releaseDetails.getVersion()));
How about using https://stackoverflow.com/questions/12627457/format-statement-in-a-string-resource-file, we might have done it in the past for progress bar too.

2020-12-24 16:56 UTC, MatkovIvan approved these changes

2020-12-24 19:01 UTC, Jamminroot approved these changes

2020-12-25 08:17 UTC, merged