Crash when direct boot
microsoft/appcenter-sdk-android pull request #1632
Opened 2022-06-10 12:56 UTC by aleksandr-dorofeev

Please have a look at our [guidelines for contributions](https://github.com/microsoft/appcenter-sdk-android/blob/develop/CONTRIBUTING.md) and consider the following before you submit the PR:

* [x] Has `CHANGELOG.md` been updated?
* [x] Are tests passing locally?
* [x] Are the files formatted correctly?
* [x] Did you add unit tests?
* [x] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?
* [ ] Did you check UI tests on the sample app? They are not executed on CI.

## Description

Added protected storage for data in direct boot mode

## Related PRs or issues

#1623 
[AB#91315](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/91315)

2022-06-10 13:10 UTC, MatkovIvan requested changes

2022-06-13 07:18 UTC, DmitriyKirakosyan commented
@aleksandr-dorofeev  I think we should also modify the existing test(s) of AppCenter.run and check that we use contact from `ApplicationContextUtils.getApplicationContext`.

2022-06-14 10:14 UTC, aleksandr-dorofeev commented
> @aleksandr-dorofeev I think we should also modify the existing test(s) of AppCenter.run and check that we use context from `ApplicationContextUtils.getApplicationContext`.

2022-06-14 10:26 UTC, MatkovIvan requested changes

2022-06-14 10:26 UTC, MatkovIvan commented on sdk/appcenter/src/test/java/com/microsoft/appcenter/AbstractAppCenterTest.java
> +        ApplicationContextUtils.class
Please sort this list alphabetically

2022-06-14 10:26 UTC, MatkovIvan commented on sdk/appcenter/src/test/java/com/microsoft/appcenter/AbstractAppCenterTest.java
> +
No blank line without comment

2022-06-14 10:26 UTC, MatkovIvan commented on sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java
> +        verify(service, never()).onStarted(eq(mContext), any(Channel.class), eq(DUMMY_APP_SECRET), isNull(), eq(true));
Same

2022-06-14 10:26 UTC, MatkovIvan commented on sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java
> +        verify(service, never()).onStarted(eq(mContext), any(Channel.class), eq(DUMMY_APP_SECRET + "a"), isNull(), eq(true));
Same

2022-06-14 10:26 UTC, MatkovIvan commented on sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java
> +        verify(AnotherDummyService.getInstance(), never()).onStarted(eq(mContext), any(Channel.class), anyString(), anyString(), anyBoolean());
Same

2022-06-15 12:10 UTC, AlexeyBudynkov approved these changes

2022-06-16 11:24 UTC, MatkovIvan commented on sdk/appcenter/src/test/java/com/microsoft/appcenter/ApplicationContextUtilsTest.java
> +        ApplicationContextUtils.isDeviceProtectedStorage(mProtectedContext);
Please add return value check

2022-06-20 09:24 UTC, MatkovIvan approved these changes

2022-06-21 06:23 UTC, DmitriyKirakosyan approved these changes

2022-06-21 06:23 UTC, merged